# Form implementation generated from reading ui file 'my_sign.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 300)
        MainWindow.setMinimumSize(QtCore.QSize(400, 300))
        MainWindow.setMaximumSize(QtCore.QSize(400, 300))
        MainWindow.setStyleSheet("QLabel {\n"
"color: green;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 90, 251, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.email_edit = QtWidgets.QLineEdit(parent=self.widget)
        self.email_edit.setMinimumSize(QtCore.QSize(100, 30))
        self.email_edit.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.email_edit.setFont(font)
        self.email_edit.setToolTip("")
        self.email_edit.setStyleSheet("QLineEdit{\n"
"    border: 4px solid #555555;\n"
"    margin-top: -1;\n"
"    margin-bottom: -1;\n"
"    border-radius: 6px;\n"
"}")
        self.email_edit.setInputMask("")
        self.email_edit.setText("")
        self.email_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.email_edit.setObjectName("email_edit")
        self.verticalLayout.addWidget(self.email_edit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.password_edit = QtWidgets.QLineEdit(parent=self.widget)
        self.password_edit.setMinimumSize(QtCore.QSize(100, 30))
        self.password_edit.setMaximumSize(QtCore.QSize(250, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.password_edit.setFont(font)
        self.password_edit.setToolTip("")
        self.password_edit.setStyleSheet("QLineEdit{\n"
"    border: 4px solid #555555;\n"
"    margin-top: -1;\n"
"    margin-bottom: -1;\n"
"    border-radius: 6px;\n"
"}")
        self.password_edit.setInputMask("")
        self.password_edit.setText("")
        self.password_edit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password_edit.setObjectName("password_edit")
        self.verticalLayout.addWidget(self.password_edit)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(40, 210, 321, 51))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_3.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_3.setMaximumSize(QtCore.QSize(400, 60))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: #8af;\n"
"padding: 10px;\n"
"border-spacing: 10px;\n"
"border-collapse: separate;\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget1)
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 45))
        self.pushButton_2.setMaximumSize(QtCore.QSize(400, 60))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: #8af;\n"
"padding: 10px;\n"
"border-spacing: 10px;\n"
"border-collapse: separate;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sign"))
        self.label.setText(_translate("MainWindow", "Company - net"))
        self.email_edit.setPlaceholderText(_translate("MainWindow", "example@gmail.com"))
        self.password_edit.setPlaceholderText(_translate("MainWindow", "password"))
        self.pushButton_3.setText(_translate("MainWindow", "Sign In"))
        self.pushButton_2.setText(_translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())